# Overrides of omarchy hypr defaults

# Steam

# Steam main window tiled
windowrule = match:class ^(steam|Steam)$, match:title ^Steam$, tile on
# Float Steam popups/menus that have empty title
windowrule = match:class ^(steam|Steam)$, match:title ^$, float on
# Float Friends & Chat
windowrule = match:class ^(steam|Steam)$, match:title ^(Friends List|Friends & Chat)$, float on

