# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # Gaps between windows
    gaps_in = 2
    gaps_out = 4
    # Use master layout instead of dwindle
    # layout = master

    border_size = 1
}

animations {
    animation = windows, 1, 1, quick, popin 87% 
    animation = fade, 1, 1, quick 
    animation = border, 1, 1, quick 
    animation = layers, 1, 1, quick 
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 0
    #active_opacity = 1.0
    #inactive_opacity = 1.0
    blur {
      enabled = false
    }
    windowrule = opacity 1 1, match:class .*
    windowrule = opacity 0.94 override 0.94 override, match:class ^(Alacritty)$

    border_part_of_window = false
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
} 
